// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/forum/api/register": {
            "post": {
                "description": "Creates a new user account, validates input fields, and establishes a session cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegistration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User successfully registered and logged in.",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation failed (e.g., weak password, invalid age).",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict: Username or email is already taken.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/session/login": {
            "post": {
                "description": "Authenticates a user using either username or email and password, then creates a session cookie.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log in a user",
                "parameters": [
                    {
                        "description": "User login credentials",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "User successfully logged in.",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or missing credentials.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Invalid username/email or password.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/session/logout": {
            "post": {
                "description": "Deletes the current user session from the database and clears the session and CSRF cookies.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out a user",
                "responses": {
                    "200": {
                        "description": "Successfully logged out (session cookie cleared)."
                    }
                }
            }
        },
        "/forum/api/session/logout-all": {
            "post": {
                "description": "Deletes all active sessions for the currently authenticated user and clears the current session cookie.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out from all devices",
                "responses": {
                    "200": {
                        "description": "Successfully logged out from all devices."
                    },
                    "401": {
                        "description": "Unauthorized: User not authenticated."
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/session/verify": {
            "get": {
                "description": "Checks if the session cookie is valid, active, and not expired. Returns user data if session is valid.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify current session status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "csrf_token": {
                                    "type": "string"
                                },
                                "user": {
                                    "$ref": "#/definitions/models.User"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized: Session cookie not found, invalid, or expired.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/user/profile": {
            "get": {
                "description": "Returns the profile data for the user associated with the active session.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Profile"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "Successful response.",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: User not authenticated."
                    }
                }
            }
        }
    },
    "definitions": {
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "The HTTP status code of the response.\nexample: 400",
                    "type": "integer"
                },
                "error": {
                    "description": "The standard HTTP status text for the code.\nexample: Bad Request",
                    "type": "string"
                },
                "message": {
                    "description": "A user-friendly message describing the specific issue.\nexample: Invalid request body or validation failed.",
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "csrf_token": {
                    "description": "The CSRF token required for subsequent protected POST/PUT/DELETE requests.\nexample: XyZ123AbC456DeF789GhI0JkL",
                    "type": "string"
                },
                "session_id": {
                    "description": "The session ID (often set as a cookie, but included here for context).\nexample: d2e9f8a7-b6c5-d4e3-f2a1-b0c9d8e7f6a5",
                    "type": "string"
                },
                "user": {
                    "description": "The details of the successfully logged-in user.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "The age of the user.\nexample: 35",
                    "type": "integer"
                },
                "created_at": {
                    "description": "The timestamp when the user account was created.\nexample: 2025-01-01T10:00:00Z",
                    "type": "string"
                },
                "email": {
                    "description": "The email address of the user.\nexample: john.doe@example.com",
                    "type": "string"
                },
                "first_name": {
                    "description": "The first name of the user.\nexample: John",
                    "type": "string"
                },
                "gender": {
                    "description": "The gender of the user (e.g., Male, Female, Other).\nexample: Male",
                    "type": "string"
                },
                "id": {
                    "description": "The unique identifier for the user.\nexample: 7b1a2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
                    "type": "string"
                },
                "last_name": {
                    "description": "The last name of the user.\nexample: Doe",
                    "type": "string"
                },
                "username": {
                    "description": "The unique username of the user.\nexample: johndoe",
                    "type": "string"
                }
            }
        },
        "models.UserLogin": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "The user's username OR email address.\nrequired: true\nexample: johndoe OR john.doe@example.com",
                    "type": "string"
                },
                "password": {
                    "description": "The user's password.\nrequired: true\nexample: secureP@ss123",
                    "type": "string"
                }
            }
        },
        "models.UserRegistration": {
            "type": "object",
            "properties": {
                "age": {
                    "description": "The user's age. Must be between 13 and 120.\nrequired: true\nminimum: 13\nmaximum: 120\nexample: 24",
                    "type": "integer"
                },
                "email": {
                    "description": "The user's email address. Must be unique and valid.\nrequired: true\nexample: register@example.com",
                    "type": "string"
                },
                "first_name": {
                    "description": "The user's first name.\nrequired: true\nexample: Jane",
                    "type": "string"
                },
                "gender": {
                    "description": "The user's gender.\nrequired: true\nexample: Female",
                    "type": "string"
                },
                "last_name": {
                    "description": "The user's last name.\nrequired: true\nexample: Smith",
                    "type": "string"
                },
                "password": {
                    "description": "The user's chosen password.\nrequired: true\nmin length: 8\nexample: secureP@ss123",
                    "type": "string"
                },
                "username": {
                    "description": "The desired unique username.\nrequired: true\nmin length: 4\nexample: new_forum_user",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/forum/api",
	Schemes:          []string{},
	Title:            "Forum Application API",
	Description:      "This is the API documentation for the forum application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
