// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/login": {
            "post": {
                "description": "Creates a new user account, validates input fields, and establishes a session cookie.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration details",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.UserRegistration"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "User successfully registered and logged in.",
                        "schema": {
                            "$ref": "#/definitions/models.Comment"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation failed (e.g., weak password, invalid age).",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict: Username or email is already taken.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/session/login": {
            "post": {
                "description": "Invalidates the user's session and clears authentication cookies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out a user",
                "responses": {
                    "200": {
                        "description": "Successfully logged out",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/auth/logout-all": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes all active sessions for the current user across all devices.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Log out from all devices",
                "responses": {
                    "200": {
                        "description": "Successfully logged out from all devices",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/register": {
            "post": {
                "description": "Creates a new user account. Accepts multipart/form-data for avatar uploads.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User password (min 8 chars, 1 letter, 1 digit)",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User first name",
                        "name": "first_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User last name",
                        "name": "last_name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "User date of birth (YYYY-MM-DD)",
                        "name": "date_of_birth",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "male, female, other, or prefer_not_to_say",
                        "name": "gender",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional: defaults to email prefix",
                        "name": "nickname",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Optional: Max 500 chars",
                        "name": "about_me",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Set to 'true' or '1' for private profile",
                        "name": "is_private",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "JPEG/PNG/GIF, max 5MB",
                        "name": "avatar",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/auth/verify": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Checks if the session cookie is valid and returns the current user's info and a fresh CSRF token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify current session",
                "responses": {
                    "200": {
                        "description": "Current user and CSRF token",
                        "schema": {
                            "$ref": "#/definitions/handlers.SessionVerifyResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/categories": {
            "get": {
                "description": "Retrieves a list of all discussion categories available on the platform.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get all categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Category"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/categories/detail": {
            "get": {
                "description": "Retrieves a specific category's details along with a list of posts belonging to it.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Categories"
                ],
                "summary": "Get category by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Category ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CategoryWithPostsResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid or missing ID",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Category not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/chat/gallery": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns a list of image metadata shared between the user and a partner. (Placeholder implementation).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Get chat gallery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID of the chat partner",
                        "name": "partner",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/chat/images": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns metadata for all images attached to a single message ID. Requires sender/receiver permission.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Get images by message",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the message",
                        "name": "messageID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/chat/images/serve/{imagePath}": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Serves the image file from disk. **Crucial**: Validates that the requester is either the sender or receiver of the message before serving.",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/gif"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Serve chat image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "The relative path to the image",
                        "name": "imagePath",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Forbidden - You don't have access to this image",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Image not found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/chat/images/stats": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns total count and total byte size of all images uploaded by the authenticated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Get user image stats",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/chat/images/upload": {
            "post": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Sends an image message to another user. Validates file type (JPEG, PNG, GIF), saves to disk, and broadcasts via WebSocket.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Upload chat image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the message recipient",
                        "name": "receiver_id",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Optional text caption (max 1000 chars)",
                        "name": "content",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Image file to send (max 5MB)",
                        "name": "chat_image",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns {message: models.MessageWithUser}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Invalid file, too large, or messaging self",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/chat/images/{imageID}": {
            "delete": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Deletes the image file, the image metadata, and the original message record. Only the sender can perform this.",
                "tags": [
                    "Messaging"
                ],
                "summary": "Delete chat image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the image to delete",
                        "name": "imageID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "403": {
                        "description": "Unauthorized: Only sender can delete",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/session/logout": {
            "post": {
                "description": "Deletes the current user session from the database and clears the session and CSRF cookies.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Create a comment",
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Comment"
                        }
                    },
                    "400": {
                        "description": "Missing PostID or Content",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Database error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/comments/{id}": {
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates the text content of an existing comment. Only the author can perform this action.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Comments"
                ],
                "summary": "Edit a comment",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Comment ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully logged out (session cookie cleared)."
                    }
                }
            }
        },
        "/forum/api/session/logout-all": {
            "post": {
                "description": "Deletes all active sessions for the currently authenticated user and clears the current session cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Send a private message",
                "parameters": [
                    {
                        "description": "Message content and receiver ID",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreateMessageRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Returns {message: models.Message}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "Validation error (e.g., messaging yourself)",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/messages/conversation": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves a paginated list of messages between current user and partner. Marks messages as read.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Messaging"
                ],
                "summary": "Get conversation history",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of the partner",
                        "name": "user_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Max messages (default 10, max 50)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Pagination offset",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully logged out from all devices."
                    },
                    "401": {
                        "description": "Unauthorized: User not authenticated."
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/session/verify": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Retrieves a full list of posts created by the logged-in user, including nested categories, comments, and reactions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentication"
                ],
                "summary": "Verify current session status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "properties": {
                                "csrf_token": {
                                    "type": "string"
                                },
                                "user": {
                                    "$ref": "#/definitions/models.User"
                                }
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error.",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/forum/api/user/profile": {
            "get": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Returns the full profile details of the currently authenticated user including avatar information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Profile"
                ],
                "summary": "Get current user profile",
                "responses": {
                    "200": {
                        "description": "Complete user profile data including avatar",
                        "schema": {
                            "$ref": "#/definitions/models.UserWithAvatar"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "CookieAuth": []
                    }
                ],
                "description": "Updates editable user profile fields (first_name, last_name, about_me, gender)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User Profile"
                ],
                "summary": "Update user profile",
                "parameters": [
                    {
                        "description": "Profile update data",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Updated user profile",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Invalid request body or validation error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized: User not authenticated."
                    }
                }
            }
        }
    },
    "definitions": {
        "handlers.CategoryInfo": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "handlers.CategoryResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PostResponse"
                    }
                }
            }
        },
        "handlers.CategoryWithPostsResponse": {
            "description": "Response containing category info and its associated post list",
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "example": 1
                },
                "name": {
                    "type": "string",
                    "example": "Technology"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Post"
                    }
                }
            }
        },
        "handlers.CommentResponse": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ReactionResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "handlers.GuestResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CategoryResponse"
                    }
                }
            }
        },
        "handlers.MyPostResponse": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CategoryInfo"
                    }
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CommentResponse"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ReactionResponse"
                    }
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "handlers.PostResponse": {
            "type": "object",
            "properties": {
                "category_id": {
                    "type": "integer"
                },
                "category_name": {
                    "description": "NEW FIELD",
                    "type": "string"
                },
                "comments": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.CommentResponse"
                    }
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "image_url": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "reactions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.ReactionResponse"
                    }
                },
                "thumbnail_url": {
                    "type": "string"
                },
                "title": {
                    "description": "Optional title field",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "handlers.ReactionResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "nickname": {
                    "type": "string"
                },
                "reaction_type": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "handlers.SessionVerifyResponse": {
            "type": "object",
            "properties": {
                "csrf_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                }
            }
        },
        "models.AvatarInfo": {
            "type": "object",
            "properties": {
                "file_path": {
                    "type": "string"
                },
                "image_id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "set_at": {
                    "type": "string"
                },
                "thumbnail_path": {
                    "type": "string"
                }
            }
        },
        "models.Category": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "The unique identifier for the category.\nexample: 1",
                    "type": "integer"
                },
                "name": {
                    "description": "The name of the category.\nexample: Technology",
                    "type": "string"
                }
            }
        },
        "models.Comment": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "The text content of the comment\nexample: This is a very insightful comment!",
                    "type": "string"
                },
                "created_at": {
                    "description": "The timestamp when the comment was created\nexample: 2025-12-21T10:00:00Z",
                    "type": "string"
                },
                "id": {
                    "description": "The unique identifier for the comment (UUID)\nexample: 550e8400-e29b-41d4-a716-446655440000",
                    "type": "string"
                },
                "post_id": {
                    "description": "The ID of the post this comment belongs to\nexample: 7b1a2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
                    "type": "string"
                },
                "updated_at": {
                    "description": "The timestamp when the comment was last updated\nexample: 2025-12-21T12:30:00Z",
                    "type": "string"
                },
                "user_id": {
                    "description": "The ID of the user who authored the comment\nexample: a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6",
                    "type": "string"
                }
            }
        },
        "models.CreateMessageRequest": {
            "type": "object",
            "required": [
                "content",
                "receiver_id"
            ],
            "properties": {
                "content": {
                    "description": "Message content\nrequired: true\nexample: Hello there!",
                    "type": "string"
                },
                "receiver_id": {
                    "description": "ID of the recipient\nrequired: true\nexample: f2g3h4i5-j6k7-l8m9-n0o1-p2q3r4s5t6u7",
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "The HTTP status code of the response.\nexample: 400",
                    "type": "integer"
                },
                "error": {
                    "description": "The standard HTTP status text for the code.\nexample: Bad Request",
                    "type": "string"
                },
                "message": {
                    "description": "A user-friendly message describing the specific issue.\nexample: Invalid request body or validation failed.",
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "csrf_token": {
                    "description": "The CSRF token required for subsequent protected requests.\nexample: XyZ123AbC456DeF789GhI0JkL",
                    "type": "string"
                },
                "id": {
                    "description": "The session ID.\nexample: d2e9f8a7-b6c5-d4e3-f2a1-b0c9d8e7f6a5",
                    "type": "string"
                },
                "user": {
                    "description": "The details of the successfully logged-in user.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                }
            }
        },
        "models.Post": {
            "type": "object",
            "properties": {
                "category_id": {
                    "description": "A list of category IDs associated with this post\nexample: [1, 2, 5]",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "content": {
                    "description": "The main body content of the post\nexample: I am trying to containerize my Go application...",
                    "type": "string"
                },
                "created_at": {
                    "description": "The timestamp when the post was created\nexample: 2025-12-29T18:00:00Z",
                    "type": "string"
                },
                "id": {
                    "description": "The unique identifier for the post (UUID)\nexample: 7b1a2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
                    "type": "string"
                },
                "title": {
                    "description": "The title of the post\nexample: How to use Go with Docker?",
                    "type": "string"
                },
                "updated_at": {
                    "description": "The timestamp when the post was last updated\nexample: 2025-12-29T19:30:00Z",
                    "type": "string"
                },
                "user_id": {
                    "description": "The ID of the user who created the post\nexample: a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6",
                    "type": "string"
                }
            }
        },
        "models.ReactionWithUser": {
            "type": "object",
            "properties": {
                "comment_id": {
                    "description": "The ID of the comment (if applicable)",
                    "type": "string"
                },
                "created_at": {
                    "description": "example: 2025-12-29T18:00:00Z",
                    "type": "string"
                },
                "nickname": {
                    "description": "The display name of the user\nexample: gopher_fan",
                    "type": "string"
                },
                "post_id": {
                    "description": "The ID of the post (if applicable)",
                    "type": "string"
                },
                "reaction_type": {
                    "description": "The type of reaction (e.g., 1 for Like, -1 for Dislike)\nexample: 1",
                    "type": "integer"
                },
                "user_id": {
                    "description": "The ID of the user who reacted\nexample: a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6",
                    "type": "string"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "about_me": {
                    "description": "A short bio or description of the user.",
                    "type": "string"
                },
                "created_at": {
                    "description": "The timestamp when the user account was created.\nexample: 2025-01-01T10:00:00Z",
                    "type": "string"
                },
                "date_of_birth": {
                    "description": "The date of birth of the user.\nexample: 1990-01-01",
                    "type": "string"
                },
                "email": {
                    "description": "The email address of the user.\nexample: john.doe@example.com",
                    "type": "string"
                },
                "first_name": {
                    "description": "The first name of the user.\nexample: John",
                    "type": "string"
                },
                "gender": {
                    "description": "The gender of the user (male, female, other, prefer_not_to_say).\nexample: male",
                    "type": "string"
                },
                "id": {
                    "description": "The unique identifier for the user.\nexample: 7b1a2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
                    "type": "string"
                },
                "is_private": {
                    "description": "Indicates if the profile is private.",
                    "type": "boolean"
                },
                "last_name": {
                    "description": "The last name of the user.\nexample: Doe",
                    "type": "string"
                },
                "nickname": {
                    "description": "The unique nickname of the user.\nexample: johndoe",
                    "type": "string"
                }
            }
        },
        "models.UserLogin": {
            "type": "object",
            "properties": {
                "login": {
                    "description": "The user's nickname OR email address.\nrequired: true\nexample: johndoe OR john.doe@example.com",
                    "type": "string"
                },
                "password": {
                    "description": "The user's password.\nrequired: true\nexample: secureP@ss123",
                    "type": "string"
                }
            }
        },
        "models.UserWithAvatar": {
            "type": "object",
            "properties": {
                "about_me": {
                    "description": "A short bio or description of the user.",
                    "type": "string"
                },
                "avatar": {
                    "description": "Avatar information retrieved from images_core via user_avatars relationship",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.AvatarInfo"
                        }
                    ]
                },
                "created_at": {
                    "description": "The timestamp when the user account was created.\nexample: 2025-01-01T10:00:00Z",
                    "type": "string"
                },
                "date_of_birth": {
                    "description": "The date of birth of the user.\nexample: 1990-01-01",
                    "type": "string"
                },
                "email": {
                    "description": "The email address of the user.\nexample: john.doe@example.com",
                    "type": "string"
                },
                "first_name": {
                    "description": "The first name of the user.\nexample: John",
                    "type": "string"
                },
                "gender": {
                    "description": "The gender of the user (male, female, other, prefer_not_to_say).\nexample: male",
                    "type": "string"
                },
                "id": {
                    "description": "The unique identifier for the user.\nexample: 7b1a2c3d-4e5f-6a7b-8c9d-0e1f2a3b4c5d",
                    "type": "string"
                },
                "is_private": {
                    "description": "Indicates if the profile is private.",
                    "type": "boolean"
                },
                "last_name": {
                    "description": "The last name of the user.\nexample: Doe",
                    "type": "string"
                },
                "nickname": {
                    "description": "The unique nickname of the user.\nexample: johndoe",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Social-network Application API",
	Description:      "This is the API documentation for the social-network application.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
