# schemaspy.properties
schemaspy.t=sqlite-xerial
schemaspy.dp=drivers/sqlite-jdbc.jar
schemaspy.db=../social-network.db
schemaspy.o=./output
schemaspy.u=root

# ADD THESE TWO LINES:
schemaspy.s=main
schemaspy.cat=%

# Optional: Disable "Ads" footer to speed up generation
schemaspy.noads=true