name: Generate Database Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Run SchemaSpy
        # This tells the runner to execute commands inside your tool folder
        working-directory: API/database/schema_doc
        run: |
          java -jar schemaspy.jar -configFile schemaspy.properties

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path must be relative to the repository root
          path: API/database/schema_doc/output

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4